### ISSUE TITLE
Ревью #1

### ISSUE THREAD

**Issue by ShkiTTer** [delet-dis/MAD-meditation#3]
1. Объявлять `lateinit` переменные в методах точно не стоит. Их вообще лучше не использовать, потому что могут приводить к неожиданным крэшам приложения. Лучше использовать `nullable` переменные. Их можно нормально проверить.

В данном случае, все вообще решается объявлением обычной переменной и зачем тут именно `lateinit` не понятно.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/SplashscreenActivity.kt#L19-L31

2. Ты используешь `ViewBinding`, поэтому отдельно хранить ссылки на `View` не нужно.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/OnboardingActivity.kt#L47-L50

3. Эту запись можно упростить. Но это уже дело вкуса, поэтому можешь этот пункт не исправлять
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/MainActivity.kt#L86
```
bundleOf(ConstantsHelper.loginResponseParcelableName to processingLoginResponse)
```

4. Ты попытался в одной из активити в `MVVM`. Похвально, но сейчас у тебя каждый раз создается новая `ViewModel` в нескольких методах. Суть `ViewModel`, чтобы она была одна. Для этого есть специальные фабрики, которые гарантируют, что она будет одна. Ее суть в том, чтобы не пропадали данные, когда активити или фрагмент пересоздаются. У тебя же это сейчас не сработает. Я бы сейчас отказался от использования `MVVM` и в будущих задания попробовал бы начать с `MVC`. И так потихоньку дойти и до `MVVM`
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/GalleryImageViewActivity.kt#L60

5. `SQL` и запросам к БД точно не место во `ViewModel`. Для этого у тебя есть `DAO` интерфейс
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/database/GalleryViewModel.kt#L25-L31

6. Тут стоит возвращать не `nullable` значение. Каждый раз проверять есть ли БД странно.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/database/GalleryDatabase.kt#L16

7. К пункту про `MVVM`. `ViewModel` у каждого фрагмента/активити должна быть своя.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/fragments/ProfileFragment.kt#L61

8. Permissions лучше запрашивать также с помощью `ActivityResultApi`, как ты получаешь изображение из галерии.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/fragments/ProfileFragment.kt#L139-L144

9. Методы внутри методов объявлять не стоит. Надо это делать внутри класса.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/fragments/ProfileFragment.kt#L156-L167

10. Во `ViewHolder` также можно и нужно использовать `ViewBinding`
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/recyclerViewAdapters/GalleryAdapter.kt#L52-L59

11. Адаптер не должен заниматься загрузкой данных. А только их отображением. Т.е. в адаптер должны были попасть уже готовые ссылки на изображения, которые ты грузишь через `Glide`
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/recyclerViewAdapters/GalleryAdapter.kt#L33-L41

12. Если поле называется также как в `JSON`, то `SerializedName` можно не использовать
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/model/LoginRequest.kt#L6

13. Сейчас при каждом запросе `retrofitService` у тебя создается новый экземпляр. Это лишнее.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/http/common/Common.kt#L8-L9

14. Константы, которые ты используешь только в одном классе стоит хранить именно в нем, а не с общими. Как раз с `SharedPreferences` так и должно быть
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/helpers/SharedPreferencesHelper.kt#L10

15. Чтобы не передавать в каждый метод `context` стоит сделать `SharedPreferencesHelper` классом, который принимает себе параметром контекст.
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/helpers/SharedPreferencesHelper.kt#L23-L25

16. Также не нужно передавать ключи в методы для `SharedPreferences`. Ключи нужно хранить в самом классе и для каждого значения лучше сделать свои методы для установки и чтения
https://github.com/delet-dis/MAD-meditation/blob/d4fb6c2eca7980b5a614b10e440742a683d66f3d/app/src/main/java/com/delet_dis/madmeditation/helpers/SharedPreferencesHelper.kt#L17-L21

17. В коде очень много операторов `!!`. Опасная штука, которую не стоит использовать, потому что приложение в любой момент может упасть.

**Comment by delet-dis** [comment]
Исправил!
